server:
  port: 8761
eureka:
  instance:
    hostname: springcloud-eureka-service  #eureka实例的主机名
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上获取服务的注册信息
    service-url:  #注册中心的地址：key-value组成
      defaultZone: http://localhost:8761/eureka/

